name: build

# on: [push, pull_request]
on:
  push:
    branches:
      - '*'
      - '!release'
  pull_request:
    branches:
      - '*'
      - '!release'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
      - name: Run the default task
        run: |
          rake && gem build *.gemspec
